feat: edit profile section added on dashboard
Matthew-Oluwajuwon/taskminder pull request #2
Opened 2023-07-27 04:18 UTC by Sammydepoj

2023-07-27 23:17 UTC, Matthew-Oluwajuwon reviewed
You didn't remember to leave comment and also instead od using ampersand, u shud have used tenary operators cuz if isEditingProfile is false we want to show the info like that

2023-07-27 23:30 UTC, Sammydepoj commented
Noted.

2023-07-28 06:57 UTC, Matthew-Oluwajuwon requested changes
so implement as discussed

2023-07-28 11:44 UTC, Matthew-Oluwajuwon approved these changes

2023-07-28 11:45 UTC, merged